### ISSUE TITLE
PowerSchool GPA

### ISSUE THREAD

**Issue by ThatXliner** [ThatXliner/skootils#37]
### Prerequisites

- [X] I have searched the [issues](https://github.com/ThatXliner/powerschool/issues) and believe that it has not already been requested (and possibly rejected)
- [X] I have made sure that this feature isn't possible with this project's plugin system and/or configuration and core changes must be made to make this happen
- [X] I agree to follow the [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)

### Feature description

Implement simple GPA calculation

**Comment by Weave-Trix** [comment]
Hi, do you need help on this?

**Comment by ThatXliner** [comment]
Nope, but thanks for the offer!
